apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.docker_hub }}/{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
          - containerPort: {{ .Values.deployment.containerPort }}
        resources:
          limits:
            cpu: {{ .Values.deployment.cpu }}
            memory: {{ .Values.deployment.memory }}